Add workflow_call action to generate the document
tier4/autoware-github-actions pull request #8
Opened 2021-11-18 07:33 UTC by KeisukeShima

2021-11-18 08:53 UTC, KeisukeShima commented
There doesn't seem to be a way to reference the shell scripts in this repository.
Therefore, I need to write the script in the workflow file.

https://github.com/tier4/autoware-documentation-proposal/runs/4248865852?check_suite_focus=true

2021-11-18 08:54 UTC, KeisukeShima commented
/cc @kenji-miyake

2021-11-18 08:59 UTC, kenji-miyake commented
@KeisukeShima How about getting scripts by `curl`? Is it impossible?

2021-11-18 09:11 UTC, KeisukeShima commented
@kenji-miyake Thanks!! This is nice idea! :100: 
https://github.com/tier4/autoware-documentation-proposal/runs/4249151187?check_suite_focus=true

2021-11-18 09:19 UTC, kenji-miyake commented on .github/create-doc-comment.sh
> +# Usage: create_doc_comment.sh <base_url> <base_branch>
```suggestion
# Usage: create-doc-comment.sh <base_url> <base_branch>
```

2021-11-18 09:19 UTC, kenji-miyake commented on .github/workflows/generate-docs.yaml
> +            https://raw.githubusercontent.com/tier4/autoware-github-actions/feature/add-generate-docs/.github/create-doc-comment.sh
How about merging the script first and referring to `main` branch here?

2021-11-18 10:33 UTC, KeisukeShima commented on .github/workflows/generate-docs.yaml
> +            https://raw.githubusercontent.com/tier4/autoware-github-actions/feature/add-generate-docs/.github/create-doc-comment.sh
Thanks for letting me know. I forgot to fix it.

d773426

2021-11-18 10:47 UTC, kenji-miyake commented on .github/workflows/generate-docs.yaml
> +      github-pages-url:
Can you get this from `mkdocs.yaml` like this?

```sh
grep -oP "site_url:\s+\K(.*)" mkdocs.yml
```

2021-11-18 23:54 UTC, kenji-miyake commented on .github/create-doc-comment.sh
> +  markdown_paths+=("$modified_file")
```suggestion
  markdown_paths+=("${modified_file//docs\//}")
```

2021-11-18 23:55 UTC, kenji-miyake commented on .github/create-doc-comment.sh
> +  markdown_paths+=("$modified_file")
You can give `docs` as an argument.

2021-11-19 02:22 UTC, kenji-miyake commented on .github/workflows/generate-docs.yaml
> +      github-pages-url:
760de30605ed29ba11e309d978436927cdd90249

2021-11-19 02:25 UTC, kenji-miyake approved these changes

2021-11-19 02:27 UTC, kenji-miyake requested changes
Waiting for the CI passes in https://github.com/tier4/autoware-documentation-proposal/pull/11

2021-11-19 04:13 UTC, KeisukeShima commented
I'm trying to figure out how to fix it...

![image](https://user-images.githubusercontent.com/19993104/142563775-1ef6fa2b-c9d9-47fb-8586-fcdc84f0313a.png)

2021-11-19 04:26 UTC, kenji-miyake commented
Probably curl is failed. You can confirm that by using `cat create-doc-command.sh`.

2021-11-19 04:27 UTC, KeisukeShima commented
@kenji-miyake Thanks! I will check the problem after this PR merged.

2021-11-19 04:31 UTC, kenji-miyake commented
Ah, it's because this PR isn't merged yet.
So let's merge!

2021-11-19 04:31 UTC, kenji-miyake approved these changes

2021-11-19 04:31 UTC, merged